### ISSUE TITLE
вопросы

### ISSUE THREAD

**Issue by Fayst2D** [30something/git_practice#1]
Ты же учишься в ФПМИ БГУ ? Мне в следующем году поступать и я бы хотел задать несколько вопросов: 
1) сколько там хороших преподов ? 
2) Кто из преподавателей параллельно работает в IT? 
3) Много ли времени уходит на домашку, лабы, и т.д. ? 
4) Душат ли матешой ? 
5) И в общем как тебе факультет ?

**Comment by 30something** [comment]
В tg могу рассказать, github не для этого придуман) - >https://t.me/thirty_something
